name:   'libfeihu Blog'
url:    'http://feihu.me'
author: 'feihu'

include:  ['_pages']

gems: [jekyll-paginate]
paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'
relative_permalinks: false

excerpt_separator: "{{ more }}"

highlighter: pygments
markdown: 'kramdown'
timezone: 'Asia/Shanghai'

analytics:
    provider: google
    google:
        tracking_id: 'UA-48817497-1'

enable_disqus: true

